name: Deployment by Repository Dispatcher
on:
  push:
    branches: [main]

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['PowerPhone/PowerPhone.github.io']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "build", "client_payload": {}}' https://api.github.com/repos/${{ matrix.repo }}/dispatches
